apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: flinkjobcluster-http
spec:
  flinkVersion: "1.14"
  image:
    name: flink:1.14.2
  jobManager:
    volumes:
      - name: usrlib
    volumeMounts:
      - mountPath: /opt/flink/usrlib
        name: usrlib
    initContainers:
      - name: downloader
        image: curlimages/curl
        command:
          ["sh", "-c", "cd /opt/flink/usrlib; curl -O ${FLINK_JOB_JAR_URI}"]
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
          - mountPath: /opt/flink/usrlib
            name: usrlib
  taskManager:
    volumes:
      - name: usrlib
    volumeMounts:
      - mountPath: /opt/flink/usrlib
        name: usrlib
    initContainers:
      - name: downloader
        image: curlimages/curl
        command:
          ["sh", "-c", "cd /opt/flink/usrlib; curl -O ${FLINK_JOB_JAR_URI}"]
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
          - mountPath: /opt/flink/usrlib
            name: usrlib
  job:
    mode: Application
    cleanupPolicy:
      afterJobSucceeds: DeleteCluster
      afterJobFails: DeleteCluster
      afterJobCancelled: DeleteCluster
    jarFile: https://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming_2.12/1.14.3/flink-examples-streaming_2.12-1.14.3-WordCount.jar
    className: org.apache.flink.streaming.examples.wordcount.WordCount
    args: ["--input", "./README.txt"]
    restartPolicy: Never
